---
title: "Spatial Bayesian models"
author: "[Andrei Wong](https://github.com/Andrei-WongE)"
date: "April 16, 2026"
format:
  html:
    theme: lux
    html-math-method: mathjax
  pdf:
    documentclass: article 
# Add table of contents
    toc: true
    toc_float: true
    toc-depth: 2
    toc-location: left
    toc-title: "On this page"
    number-sections: true
# By default smooth scroll is not enabled
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: true
    highlight-style: github
# Fold code (initially hidden)
    code-fold: true
    code_download: yes
    code-link: true
    code-block-bg: true
    code-block-border-left: "#ADBBCB"
    table-captions: true 
    tbl-cap-location: margin
    reference-location: margin
    citation-location: margin
# Text for footer
    include-after-body: footer.html
    
citation:
  type: post
  url: "https://github.com/Andrei-WongE/spatial_bayes_sandbox"
  
# Allow for highlighting text. \hl{highlight} text inline.Or \hl{\textbf{highlight}} with bold face.
# Allows fort commenting using hypothesis
comments:
  hypothesis: true 

execute:
  warning: false
  message: false
  #freeze: auto  # re-render only when source changes
---

# Set-up

```{r}
#| label: timestamp-setup
#| echo: false

knitted_when <- format(Sys.Date())
knitted_where <- knitr::current_input()
knitted_with <- packageVersion("knitr")
knitted_doc_url <- downlit::autolink_url("knitr::knit()")
```

Note updated on `r knitted_when` from `r knitted_where` with knitr version `r knitted_with`.

::: callout-note
## General set-up of the program.

These notes make use of the following R packages and general set-up.

```{r}
#| label: set-up

  if (!require("pacman")) {
  install.packages("pacman")
  }

  pacman::p_load(tidyverse 
                 ,tidylog
                 ,Cairo
                 ,here
                 ,dplyr
                 ,htmltools
                 ,SpatialEpi # for pennLC data
                 ,crsuggest  # Suggest CRS information for spatial data
                 ,ggplot2
                 ,ggnewscale # For multiple fill and colour scales in ggplot2
                 ,sf         # DONT'T FORGET uses the s2geometry library
                 ,leaflet    # JavaScript libraries for interactive maps
                 ,leafem     # Extensions for leaflet 
                 ,knitr
                 ,ragg       # Graphic devices based on the AGG library
                 ,downlit    # For syntax highlighting and automatic linking
                 ,git2r      # Provides access to 'Git' repositories
                 ,xfun       # For alternative Session Info
                 )
  
  #pacman::p_update()         # Update out-of-date packages

  options(scipen = 100, digits = 2)             # Prefer non-scientific notation
  
  knitr::opts_chunk$set( dev       = "ragg_png"
                        ,fig.path  = "Figs/"
                        ,dpi       = 600
                        ,fig.width = 10
                        ,fig.hight = 12
  # Automatically formatting code using styler
                        ,tidy      = "styler"
)

```
:::

# Spatial Bayesian models

## CARBayes Demo

This example is adapted from the following article by [Dr Paula Moraga](https://journal.r-project.org/archive/2018/RJ-2018-036/RJ-2018-036.pdf)

```{r}
#| label: data
#| include: false

source(here("Install.R")) # Has fillmap.R as dependency

# dependencies ‘Rgraphviz’, ‘graph’ are not available

# library(SpatialEpi)  # for pennLC [rdocumentation](https://www.rdocumentation.org/packages/SpatialEpi/versions/1.2.8/topics/pennLC)


```

```{r}
data(pennLC)
names(pennLC)
head(pennLC$data)
head(pennLC$smoking)
```

```{r}
# Add observed cases
pennLC$data <- pennLC$data %>%
  tibble() %>%
  group_by(county) %>%
  mutate(obs = sum(cases)) %>%
  ungroup()

# Add expected cases
pennLC$data <- pennLC$data %>%
  group_by(race, gender, age) %>%
  mutate(
    pop.strata   = sum(population),
    cases.strata = sum(cases)
  ) %>%
  group_by(county) %>%
  mutate(
    expected = population * cases.strata / pop.strata,
    expected = sum(expected)
  ) %>%
  ungroup()

# Summarise observed and expected; add SIR
pennLC$data <- pennLC$data %>%
  select(county, obs, expected) %>%
  distinct() %>%
  mutate(SIR = obs / expected) %>%
  left_join(pennLC$smoking, by = "county")
```

```{r}
# Create sf object from SpatialPolygons
map <- st_as_sf(pennLC$spatial.polygon) %>%
  st_transform("+proj=longlat +datum=WGS84")

map <- cbind(map, pennLC$data)

pal <- colorNumeric(palette = "YlOrRd", domain = map$SIR)
```

```{r}
# Observed SIR map
leaflet(map) %>%
  addTiles() %>%
  addPolygons(
    color       = "grey",
    weight      = 1,
    fillColor   = ~pal(SIR),
    fillOpacity = 0.7
  ) %>%
  addLegend(
    pal      = pal,
    values   = ~SIR,
    opacity  = 0.7,
    title    = "SIR",
    position = "bottomright"
  )
```

```{r}
# Labels
labels <- sprintf(
  "<strong>%s</strong><br/>Observed: %s <br/>Expected: %s 
   <br/>Smokers proportion: %s <br/>SIR: %s",
  map$county,
  map$obs,
  round(map$expected, 2),
  map$smoking,
  round(map$SIR, 2)
) %>%
  lapply(htmltools::HTML)

leaflet(map) %>%
  addTiles() %>%
  addPolygons(
    color           = "grey",
    weight          = 1,
    fillColor       = ~pal(SIR),
    fillOpacity     = 0.7,
    highlightOptions = highlightOptions(weight = 4),
    label           = labels,
    labelOptions    = labelOptions(
      style    = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    pal      = pal,
    values   = ~SIR,
    opacity  = 0.7,
    title    = "SIR",
    position = "bottomright"
  )
```

```{r}
# Adjacency matrix
W <- st_touches(map) %>%
  as.matrix() * 1

M.burnin <- 10000
M        <- 5000

set.seed(111)
MCMC <- S.CARbym(
  formula  = obs ~ 1 + offset(log(expected)),
  data     = map,
  family   = "poisson",
  W        = W,
  burnin   = M.burnin,
  n.sample = M.burnin + M,
  verbose  = FALSE
)

print(MCMC$summary.results)
```

```{r}
# Posterior SIR and summary
y.fit <- MCMC$samples$fitted
SIR   <- t(t(y.fit) / map$expected)

map$SIR.50  <- apply(SIR, 2, median)
map$SIR.025 <- apply(SIR, 2, quantile, 0.025)
map$SIR.975 <- apply(SIR, 2, quantile, 0.975)
map$PP      <- apply(SIR, 2, function(x) length(which(x > 1))) / M

labels <- sprintf(
  "<strong>%s</strong> <br/>Observed: %s <br/>Expected: %s <br/>
   Smoker proportion: %s <br/>SIR: %s <br/>RR: %s (%s, %s) <br/>PP: %s",
  map$county,
  map$obs,
  round(map$expected, 2),
  map$smoking,
  round(map$SIR, 2),
  round(map$SIR.50, 2),
  round(map$SIR.025, 2),
  round(map$SIR.975, 2),
  round(map$PP, 3)
) %>%
  lapply(htmltools::HTML)

leaflet(map) %>%
  addTiles() %>%
  addPolygons(
    color           = "grey",
    weight          = 1,
    fillColor       = ~pal(SIR.50),
    fillOpacity     = 0.7,
    highlightOptions = highlightOptions(weight = 4),
    label           = labels,
    labelOptions    = labelOptions(
      style    = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    pal      = pal,
    values   = ~SIR.50,
    opacity  = 0.7,
    title    = "Relative Risk",
    position = "bottomright"
  )
```
